language: java
sudo: false

jdk:
  - oraclejdk7

install: true
script: ./travis.sh

env:
  matrix:
    - TARGET=CI

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar'

notifications:
  email: false
